src/Entity/Employees.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EmployeesRepository")
 */
class Employees
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $middlename;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_of_birth;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $inn;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $snils;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Organizations", inversedBy="employees")
     */
    private $organization;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getMiddlename(): ?string
    {
        return $this->middlename;
    }

    public function setMiddlename(?string $middlename): self
    {
        $this->middlename = $middlename;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(?\DateTimeInterface $date_of_birth): self
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function getInn(): ?string
    {
        return $this->inn;
    }

    public function setInn(?string $inn): self
    {
        $this->inn = $inn;

        return $this;
    }

    public function getSnils(): ?string
    {
        return $this->snils;
    }

    public function setSnils(?string $snils): self
    {
        $this->snils = $snils;

        return $this;
    }

    public function getOrganization(): ?Organizations
    {
        return $this->organization;
    }

    public function setOrganization(?Organizations $organization): self
    {
        $this->organization = $organization;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getOrganization()->getId();
    }
}

src/Form/EmployeesType.php
<?php

namespace App\Form;

use App\Entity\Employees;
use App\Entity\Organizations;
use App\Form\OrganizationsType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmployeesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstname')
            ->add('middlename')
            ->add('lastname')
            ->add('date_of_birth')
            ->add('inn')
            ->add('snils')
            ->add('organization', EntityType::class, [
                'class'    => Organizations::class,
                'choice_label' => 'name'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Employees::class,
        ]);
    }
}

src/Controller/EmployeesController.php
<?php

namespace App\Controller;

use App\Entity\Employees;
use App\Form\EmployeesType;
use App\Form\UploadedFilesType;
use App\Repository\EmployeesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/employees")
 */
class EmployeesController extends AbstractController
{
    /**
     * @Route("/", name="employees_index", methods={"GET"})
     */
    public function index(EmployeesRepository $employeesRepository): Response
    {
        return $this->render('employees/index.html.twig', [
            'employees' => $employeesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="employees_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $employee = new Employees();
        $form = $this->createForm(EmployeesType::class, $employee);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($employee);
            $entityManager->flush();

            return $this->redirectToRoute('employees_index');
        }

        return $this->render('employees/new.html.twig', [
            'employee' => $employee,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="employees_show", methods={"GET"})
     */
    public function show(Employees $employee): Response
    {
        return $this->render('employees/show.html.twig', [
            'employee' => $employee,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="employees_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Employees $employee): Response
    {
        $form = $this->createForm(EmployeesType::class, $employee);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('employees_index');
        }

        return $this->render('employees/edit.html.twig', [
            'employee' => $employee,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="employees_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Employees $employee): Response
    {
        if ($this->isCsrfTokenValid('delete'.$employee->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($employee);
            $entityManager->flush();
        }

        return $this->redirectToRoute('employees_index');
    }

//    /**
//     * @Route("/upload", name="upload", methods={"GET","POST"})
//     */
//    public function uploadFile(Request $request): Response
//    {
//        $file = new UploadedFile();
//        $form = $this->createForm(UploadedFilesType::class, $file);
//    }
}

templates/employees/_delete_form.html.twig
<form method="post" action="{{ path('employees_delete', {'id': employee.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ employee.id) }}">
    <button class="btn">Delete</button>
</form>

templates/employees/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/employees/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Employees{% endblock %}

{% block body %}
    <h1>Edit Employees</h1>

    {{ include('employees/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('employees_index') }}">back to list</a>

    {{ include('employees/_delete_form.html.twig') }}
{% endblock %}

templates/employees/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Список сотрудников{% endblock %}

{% block body %}
    <h1>Список сотрудников</h1>
    <a href="{{ path('organizations_index') }}">Список организаций</a>
    <a href="{{ path('employees_index') }}">Список сотрудников</a>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Организация</th>
                <th>Имя</th>
                <th>Отчество</th>
                <th>Фамилия</th>
                <th>Дата рождения</th>
                <th>ИНН</th>
                <th>СНИЛС</th>
            </tr>
        </thead>
        <tbody>
        {% for employee in employees %}
            <tr>
                <td>{{ employee.id }}</td>
                <td>{{ employee.organization.name }}</td>
                <td>{{ employee.firstname }}</td>
                <td>{{ employee.middlename }}</td>
                <td>{{ employee.lastname }}</td>
                <td>{{ employee.dateOfBirth ? employee.dateOfBirth|date('Y-m-d') : '' }}</td>
                <td>{{ employee.inn }}</td>
                <td>{{ employee.snils }}</td>
                <td>
                    <a href="{{ path('employees_show', {'id': employee.id}) }}">Подробнее</a>
{#                    <a href="{{ path('employees_edit', {'id': employee.id}) }}">edit</a>#}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">Записей не найдено</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('employees_new') }}">Добавить нового сотрудника</a>

    {% include 'upload_form.html.twig' %}

{% endblock %}

templates/employees/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Employees{% endblock %}

{% block body %}
    <h1>Create new Employees</h1>

    {{ include('employees/_form.html.twig') }}

    <a href="{{ path('employees_index') }}">back to list</a>
{% endblock %}

templates/employees/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Employees{% endblock %}

{% block body %}
    <h1>Карточка сотрудника <br> {{ employee.firstName }} {{ employee.middlename }} {{ employee.lastname }}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ employee.id }}</td>
            </tr>
            <tr>
                <th>Организация</th>
                <td>{{ employee.organization.name }}</td>
            </tr>
            <tr>
                <th>Имя</th>
                <td>{{ employee.firstname }}</td>
            </tr>
            <tr>
                <th>Отчество</th>
                <td>{{ employee.middlename }}</td>
            </tr>
            <tr>
                <th>Фамилия</th>
                <td>{{ employee.lastname }}</td>
            </tr>
            <tr>
                <th>Дата рождения</th>
                <td>{{ employee.dateOfBirth ? employee.dateOfBirth|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>ИНН</th>
                <td>{{ employee.inn }}</td>
            </tr>
            <tr>
                <th>СНИЛС</th>
                <td>{{ employee.snils }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('employees_index') }}">Вернуться к списку сотрудников</a>

{#    <a href="{{ path('employees_edit', {'id': employee.id}) }}">edit</a>#}

{#    {{ include('employees/_delete_form.html.twig') }}#}
{% endblock %}